version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: |
            python -m pip install --upgrade pip
      - run:
          name: Run tests
          command: |
            python -m unittest discover -s . -p "test_upper_name.py"

workflows:
  version: 2
  test:
    jobs:
      - test
