version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8  # Use a Docker image with Python 3.8
    steps:
      - checkout  # Check out the source code
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt  # Install dependencies from requirements.txt
      - run:
          name: Run tests
          command: |
            python -m unittest discover -s . -p "test_upper_name.py"  # Run the tests

workflows:
  version: 2
  test:
    jobs:
      - test
